
CREATE TABLE users (
  username VARCHAR(45) NOT NULL PRIMARY KEY,
  password VARCHAR(45) NOT NULL ,
  enabled INTEGER NOT NULL
);

CREATE TABLE user_roles (
  user_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
  username VARCHAR(45) NOT NULL,
  role VARCHAR(45) NOT NULL
);

INSERT INTO users(username,password,enabled)
VALUES ('mkyong','123456', 1);
INSERT INTO users(username,password,enabled)
VALUES ('alex','123456', 1);

INSERT INTO user_roles (username, role)
VALUES ('mkyong', 'ROLE_USER');
INSERT INTO user_roles (username, role)
VALUES ('mkyong', 'ROLE_ADMIN');
INSERT INTO user_roles (username, role)
VALUES ('alex', 'ROLE_USER');
